[{{ input_name }}_input]
type="ProcessInput"
ticker_interval = {{ input.get('ticker_interval', 30) }}
{%- if input.decoder is defined %}
decoder = "{{ input.decoder }}"
{%- endif %}
{%- if input.splitter is defined %}
splitter = "{{ input.get('splitter', 'NullSplitter') }}"
{%- endif %}
stdout = {{ input.get('stdout', true)|lower }}
stderr = {{ input.get('stderr', true)|lower }}
